### ISSUE TITLE
Sustaining an FO should always require super-majority support

### ISSUE THREAD

**Issue by palemieux** [w3c/w3process#631] opened 2022-09-19 22:52 UTC
As noted at https://github.com/w3c/AB-memberonly/blob/master/documents/FormalObjectionCouncilGuide.md#ii-burden-of-proof, an FO is essentially a minority opinion since it questions a consensus decision.

Sustaining an FO should therefore require a super-majority in the FO: there should be twice as many yes than no, and the number of yes should be over a certain threshold, e.g. 50%. The latter is to account for abstentions.

In particular, a decision should not be made by a simple majority, as currently suggested at https://www.w3.org/Consortium/Process/Drafts/director-free/#council

**Comment by fantasai** [comment] 2022-09-21 17:41
Closing as duplicate of https://github.com/w3c/w3process/issues/280

**Closed by fantasai** 2022-09-21 17:41 UTC
Labels: Closed: Duplicate, Director-free: FO/Council, Director-free (all)

**Comment by frivoal** [comment] 2023-03-03 05:32
@palemieux, since you opened the issue and we are wrapping up this cycle, I'd like to confirm: do you agree that this issue, being about whether a supermajority should be required for the council to make the decision to sustain, is indeed a duplicate of https://github.com/w3c/w3process/issues/280, which was about what how to make decisions if the council has less than consensus, and which considered whether a supermajority should be required?

**Comment by palemieux** [comment] 2023-03-04 23:05
Yes, good to close.
