### ISSUE TITLE
Clarify that tooling must be accessible for people with disabilities

### ISSUE THREAD

**Issue by brewerj** [w3c/w3process#537] opened 2021-06-08 20:34 UTC
Currently in the tooling section there is a bullet stating: 

> "Any tooling used by the group for producing its documentation and deliverables or for official group discussions should be usable without additional cost by all who wish to participate, to allow their effective participation."

It is not clear from this that tooling must be accessible for people with disabilities who contribute to the W3C community. The term "usable... by all" doesn't have the clarity or get the outcome needed, and W3C Team are having to scramble more and more often to deal with barriers from tools, or arrange assessments, etc. 

Here is one possibility: 

""Any tooling used by the group for producing its documentation and deliverables or for official group discussions should be accessible for people with disabilities according to relevant standards, and usable without additional cost by all who wish to participate, to allow their effective participation."

Thoughts welcome.

**Comment by brewerj** [comment] 2021-06-08 21:51
Shorter suggestion: 

"Any tooling used by the group for producing its documentation and deliverables or for official group discussions should be accessible for people with disabilities."

Rationale: In the interest of brevity, it makes sense to prioritize, and I think that's probably the more essential priority than "usable without additional cost" especially given that there's not a clear standard to point to on that. I suspect that groups will debate the usability of potential tools regardless of an expectation that they do so; but I do not expect that groups will consider accessibility of tools without an explicit prompt to do so, at least given the preponderance of history on how accessibility in tooling is regarded.

**Comment by fantasai** [comment] 2021-06-09 17:13
Fwiw, the main point of this rule was about tools being usable, rather than the cost of them (that phrase was something Tantek asked us to add). I think it's good to be more explicit about persons with disabilities, though, so I agree we should say something specifically about that.

However, that's not the only case this rule was intended to cover: also cases of e.g. services being unavailable in certain geographies, or other problems (TOS saying "citizens of countries X, Y, and Z are not allowed to use this service", which I've run into at one point), so we can't change it to *only* talk about accessibility to people with disabilities here.

**Comment by frivoal** [comment] 2021-07-14 15:01
Addressed by landing #539

**Closed by frivoal** 2021-07-14 15:01 UTC
Labels: Closed: Accepted
