### ISSUE TITLE
Member submissions

### ISSUE THREAD

**Issue by jeffjaffe** [w3c/w3process#169] opened 2018-02-23 14:13 UTC
Section 10 of the process document has not been update to reflect CGs.  Here is one suggested edit.

s/Documents in a Member Submission are developed outside of W3C. These documents are not part of the technical report development process (and therefore are not included in the index of W3C technical reports). Members wishing to have documents developed outside of W3C published by W3C must follow the Member Submission process./Documents in a Member Submission are developed outside of the W3C technical development process (and therefore are not included in the index of W3C technical reports). /

**Comment by vfournier17** [comment] 2018-02-27 22:41
@jeffjaffe Are you referring to CG documents that would be contributed to a W3C WG?

**Comment by jeffjaffe** [comment] 2018-02-28 00:03
@vfournier17 Section 10 describes how Members may submit documents that were created outside of W3C.  The proposed edit would permit Members to submit documents that were created inside of W3C, but outside of the WG process - e.g. documents developed in CGs.  These submissions are not made to WGs per se.

**Comment by vfournier17** [comment] 2018-02-28 01:50
@jeffjaffe It seems more likely that a non-Member (such as a CG participant) would want to submit a technical report developed outside the W3C to a WG.  For example, a CG develops a technical paper they'd like to transition to a WG for possible use in a specification, and no one in the CG is a W3C Member.  The Member Submission process couldn't be used for this scenario, so how would this be handled?  Would the CG participants be required to make their contribution through a Member (and would Members want to do this?), or would they all need to become W3C Members before making the contribution?

**Comment by jeffjaffe** [comment] 2018-02-28 14:05
@vfournier17 I agree that when there is a WG for a CG spec, that it is ideal for that spec to be referenced in the WG Charter, rather than taking the Member submission route.  But there could be specs where there is no WG.  In that case, Members should be able to use the Member submission feature.

**Comment by dwsinger** [comment] 2018-02-28 21:38
This issue seems to be titled "member submissions" (a well-known process) and yet discusses CGs (a different well-known process, covered by #17) and seems to be entangling getting IPR commitments from non-WG members, which is covered by #67. So I am lost.  What is this issue, and how does it differ from #17 and #67?

**Comment by jeffjaffe** [comment] 2018-03-01 02:14
@dwsinger Sorry for not clearly stating the issue.

Currently, Member submissions are for "Documents ... developed outside of W3C".

Today, there are use cases for documents developed in a CG (and hence inside of W3C) for Members to want them to be Member submissions.

Issue #169 proposes a simple text fix to Section 10 of the process document to enable this use case.

**Comment by dwsinger** [comment] 2018-03-07 20:03
I don't think that the member submission process (which, I think, presumes one or a few originators of a document) is a great tool to use for the CG->WG transfer. A better tool (though remarkably hard to get people to use it) is the Final Spec. Agreement, IMHO.

**Comment by jeffjaffe** [comment] 2018-03-07 20:49
@dwsinger I don't disagree with you that the member submission process is not the best for CG --> WG transfer.

But I'm mindful of the fact that it could be used in some cases, so I just want to make it possible.

**Comment by dwsinger** [comment] 2018-04-11 15:47
see #180 as a more general problem (to which this may be the or part of the answer)

**Comment by michaelchampion** [comment] 2018-04-11 16:13
I like @jeffjaffe 's simple fix.  CGs may be part of "W3C" but they don't operate under the Process. The simplest change would be to clarify the language, then allow the submission process for the W3C members in a CG to formally submit a spec to W3C for standardization. It's not necessary -- specs have moved from CGs to WGs by other means, and the CG IPR policy was designed to facilitate this -- but might be useful in some scenario.

**Comment by vfournier17** [comment] 2018-04-12 00:42
I think we should have a process for CGs, etc. to address some of these issues.  But a document in a CG cannot be on the W3C Recommendation track.

**Comment by nigelmegitt** [comment] 2018-04-16 13:56
>  But a document in a CG cannot be on the W3C Recommendation track.

@vfournier17 How would you classify something like WebVTT that claims to be a CG document but is also on the Rec track in TTWG? There's one GitHub repo. And there's disagreement amongst members of both the WG and the CG (i.e. individuals who are members of both) about whether it should state that it's a CG document or not. 

It seems that the way that contributions are handled is the distinguishing factor, rather than the group that receives those contributions.

**Comment by frivoal** [comment] 2018-10-02 02:35
Made https://github.com/w3c/w3process/pull/212 to close the issue as reported by Jeff. Keeping the apparent claim that Member submissions were the only way to get things into the W3C was not helpful.

As to the discussion of whether CGs and transition from CGs are properly managed, that's a separate thing, and I encourage @nigelmegitt and @vfournier17 to open separate issues if you'd like to pursue that further.

**Closed** 2018-10-03 14:39 UTC
Labels: Agenda+, PendingReview
