### ISSUE TITLE
Community Groups

### ISSUE THREAD

**Issue by jeffjaffe** [w3c/w3process#139] opened 2017-12-06 18:06 UTC
Should CGs be discussed in Process 2019?

**Comment by chaals** [comment] 2017-12-06 19:04
See also #17

**Comment by chaals** [comment] 2017-12-06 19:04
> Should CGs be discussed in Process 2019?

IMHO, yes

**Comment by dwsinger** [comment] 2017-12-14 22:49
@jeffjaffe is this a dup of #17 or is it asking a new question?

**Comment by jeffjaffe** [comment] 2017-12-14 22:53
It's a dup.  Which Chaals noticed right away. See above.

**Comment by dwsinger** [comment] 2017-12-14 23:20
closing as a duplicate of #17

**Closed by dwsinger** 2017-12-14 23:20 UTC
Labels: duplicate
