### ISSUE TITLE
MoUs need splitting between formal contractual relationships, and true memoranda of understanding

### ISSUE THREAD

**Issue by dwsinger** [w3c/w3process#673] opened 2022-11-21 19:30 UTC
In the Process:

> For purposes of the W3C Process, a Memorandum of Understanding (MoU) is a formal agreement or similar contractual framework between W3C and another party or parties, other than between W3C and W3C members for the purposes of membership, and other agreements related to the ordinary provision of services for the purpose of running W3C, that specifies rights and obligations of each party toward the others. These rights and obligations may include joint deliverables, an agreed share of technical responsibilities with due coordination, and/or considerations for confidentiality and specific IPR. The agreement may be called something other than a “Memorandum of Understanding”, and something called a “Memorandum of Understanding” might not be an [MoU](https://www.w3.org/Consortium/Process/Drafts/#mou) for the purposes of the Process.

However, formal contractual relationships are probably more the domain of the Board (unless they are 'trivial', which would need defining), while true MoUs that merely document what we agree is our joint understanding ("we understand that you expect to do X and expect us to do Y") are probably not.

This needs disentangling a little.

**Comment by frivoal** [comment] 2022-11-22 04:58
This seems to me to be a duplicate of #670. Any reason to treat them separately?

**Comment by dwsinger** [comment] 2022-11-22 05:08
Yes. Sorry

**Closed** 2022-11-22 05:59 UTC
Labels: Closed: Duplicate, Commenter Response Pending
