### ISSUE TITLE
Are there Private Working Drafts?

### ISSUE THREAD

**Issue by LJWatson** [w3c/w3process#85] opened 2017-09-11 15:22 UTC
Is there any such thing as a Working Draft (or First Public Working Draft) that is not public? If there isn't, the word "public" in the title seems superfluous.

**Comment by dwsinger** [comment] 2017-09-11 17:15
I think some WDs of some WGs can be member-only, not public...

**Comment by chaals** [comment] 2017-09-11 18:19
People can make private whatever they want. "Working Drafts" as used by the Process means Public "Working Drafts", and vice versa. I think this issue is a duplicate of #84

**Comment by LJWatson** [comment] 2017-09-11 18:53
It's not entirely a duplicate, no. #84 asked for consistent use of either Working Draft or Public Working Draft. This issue queries whether the word "Public" is needed in either "First Public Working Draft" or "Public Working Draft".

**Comment by chaals** [comment] 2017-09-21 11:25
I agree that we need consistent terminology, but think the question of whether that includes the "P{ublic" bit is an integral part of that issue, to the extent that we shouldn't separate the decisions but resolve them at the same time. I'm therefore going to merge this issue into #84, and close this part.

**Closed by chaals** 2017-09-21 11:25 UTC
