### ISSUE TITLE
Substantive changes undefined for Charter, Process reviews, and things other than specifications

### ISSUE THREAD

**Issue by dwsinger** [w3c/w3process#28] opened 2017-04-21 18:54 UTC
Transferred from https://www.w3.org/community/w3process/track/issues/176
State: Raised

**Comment by dwsinger** [comment] 2017-08-18 16:21
we need text proposals, please. editors to check that links correctly identify where terms are defined

**Comment by dwsinger** [comment] 2018-01-10 17:40
Perhaps this needs defining in the possible Terms and Definitions section?

**Comment by frivoal** [comment] 2018-10-02 09:46
I think this issue has actually several sub parts:
1. "Substantive change" and "editorial change" are only defined for specs, not for charters
2. The usage of the term "editorial change" is inconsistent, and some place contrast Substantive changes to "minor changes" instead of "editorial changes".
3. Daniel objects to step 2 of of 7.1.2 which allows the Director to make Substantive changes to charters or specs without returning the proposal for additional work.

I have made a pull request to solve 1 and 2: https://github.com/w3c/w3process/pull/217. I expect we might quibble on the details, but probably not on the principle.

As for 3, I first thought that this was best addressed as part of #182, but actually, there is a much simpler solution, which I have proposed in a separate pull request (https://github.com/w3c/w3process/pull/218): simply delete step 2 of 7.1.2. Making any substantive change to a document after the AC has voted on it pretty much invalidates the vote, as there is not reliable way of knowing how people would have voted had that change been included originally. We can (and should) go into further details as part of #182, but for now, just removing this possibility seems a good idea.

**Comment by frivoal** [comment] 2018-10-02 12:31
update: I've completed the https://github.com/w3c/w3process/pull/217 PR to define editorial vs substantive for the process in addition to for charters.

**Comment by dwsinger** [comment] 2018-10-03 23:09
I agree that changes to scope or deliverables are the very essence of substantive.  Dates are almost certainly so as well.

Is there room here for "if anyone thinks it's substantive, it's substantive"? That is, for things in the grey areas, the Director writes "I propose doing X and I think it's not substantive; if anyone disagrees, say so, and we'll put the revised text to formal review".

As an aside, I'd like to keep the text as short as possible, of course, and give us as much latitude as possible...

**Comment by frivoal** [comment] 2018-10-04 02:03
I'm starting to think that splitting this PR into two may not have been a good idea after all, as the question of what is or isn't substantive is not that detached from what the Director is or isn't allowed to change by himself.

So far, we have 2 categories of changes (editorial / substantive), and 3 categories of actions (fix unilaterally without saying so  fix unilaterally with a rationale / sent back to work). For the sake of this discussion, I'll just call "minor substantive" those issue that the director can fix himself as long as he justifies it, and "major substantive" those that get returned for more work. We can bikeshed the terms later if necessary.

Here is the process as it is today:

|  | Editorial | Minor substantive | Major substantive|
|-|-|-|-|
|  | The Director can  change without telling anyone | The Director can change unilaterally, but must provide rationale | The Director must send back to work and to re-vote |
| Specs | fixing typos, fixing broken markup, clarifying informative notes, fixing bugs in informative examples| Everything else | up to the Director |
| Charters | undefined | undefined | up to the Director|
| Process | undefined | undefined| up to the Director|

I think the ability of the director to change absolutely anything unilaterally is a problem, and for charters and the process, the fact that it is unclear what changes he even has to explain at all is also a problem.

For Charters and the Process it is maybe debatable, but for specs especially, I do not quite see why the director needs to be able to make any normative change unilaterally.

The fact that the Director is a reasonable person unlikely to abuse his powers does not justify giving him absolute power to change anything at all.

What I propose instead:

|  | Editorial | Minor substantive | Major substantive|
|-|-|-|-|
|  | The Director can change without telling anyone | The Director can change unilaterally, but must provide rationale | The Director must send back to work and to re-vote |
| Specs | fixing typos, fixing broken markup | clarifying informative notes, fixing bugs in informative examples | Everything else |
| Charters | fixing typos, fixing broken markup | clarifying informative notes / sections<br>extending the duration of a charter (since the Director can already do that based on 5.2.5 anyway)| Everything else|
| Process | fixing typos, fixing broken markup |  clarifying informative notes / sections | Everything else|

I hope that the proposal to not leave things totally undefined, as well as the proposal to have 3 categories, one of which includes things the director **must** send to rework and re-vote if he wishes to change, should not be particularly controversial.

As for what we fit in each of the 3 categories, I think there's more room for discussion. My position is probably quite on the strict side, though I don't think it is unreasonable in the light of the past controversies.

Based on what @dwsinger suggested, I would also be open to putting more things in category 2 if anyone complaining after the fact (within a certain time period) automatically reclassifies them as category 3, sends the proposal back to work and requires a revote.

**Comment by chaals** [comment] 2018-10-08 15:32
Charters should be able to say whether deliverables can be added, within the scope, by decision of the WG, Director, or only on renewal of the charter.

I would also put fixing inconsistencies in the category of "can do, must provide rationale and they can be challenged to force an AC review". (For that matter, in specs too)

**Comment by wseltzer** [comment] 2018-10-12 17:22
I have proposed an update to the Guide to add more detail: PR https://github.com/w3c/Guide/pull/31 Issue https://github.com/w3c/Guide/issues/32

As has been discussed in the CG calls, the proposed change to Process would not appear to address the situation that prompted concern, and Team's process for handling charter reviews has added significant re-review requirements since that time. 

I recommend that we continue to fix things in the Guide and improve our processing there, rather than committing un-tested changes to the formal Process document.

**Comment by frivoal** [comment] 2018-10-20 16:40
I don't think that is sufficient.

While I am totally happy to argue about the specific text, I think there's a fundamental bug in the process as it is.

It tries to define two categories of changes, and to say that for one of the categories (substantive changes), the director MUST do certain things. But by leaving the two categories undefined for charters and for the process, we leave it to the appreciation of the director which change fall in which category, then this isn't a MUST at all.

So no, I don't think doing this in guidelines is appropriate. Guidelines are appropriate to establish jurisprudence and consistency in the way the director and the team acts within the bounds of the things they can/must do. They are not appropriate to define what is or isn't in their power to do.

**Comment by frivoal** [comment] 2018-10-21 20:58
I think that'd be an improvement over the currently undefined state, so I'd be in favor.
We need something similar for the substantive change to the process, though.

And I still think that we also need to make it so that some of the changes need to be re-run by the AC. Currently all that is required for substantive changes is that the Director gives a rationale for what he changes, but he has the right to change anything. Without returning to a vote. I don't think that's right.

**Comment by wseltzer** [comment] 2018-10-22 09:39
It seems we disagree strongly enough that we shouldn't aim this at Process 2019.

**Comment by frivoal** [comment] 2018-11-05 23:51
I still want to do this, but I don't see how we can get to agreement before the deadline for Process 2019, so removing Agenda+ for now.

**Comment by dwsinger** [comment] 2019-04-22 21:01
see also #243

**Comment by frivoal** [comment] 2020-03-11 04:58
As per https://www.w3.org/2020/01/29-w3process-minutes.html and https://www.w3.org/2020/02/12-w3process-minutes.html, this issue is deferred to a subsequent cycle of the Process.

**Comment by jeffjaffe** [comment] 2020-07-14 13:05
A useful practical definition of a "substantive" change is a change - that in the judgement of the Director - would plausibly result in reviewers changing their response to a WBS poll (most notably if it would result in a formal objection).   This may not have the rigor some are looking for.

**Comment by dwsinger** [comment] 2020-07-14 15:03
Combining @jeffjaffe 's suggestion with my two above, yields a short list of things are normally substantive, a short list of things that normally are not, and the ability of someone in the team to make a judgment call on grey areas, which is announced (to the AC). If they think something is non-substantive, and anyone in the AC disagrees, we go with the more conservative view. Is that a lightweight enough process?

**Comment by dwsinger** [comment] 2020-08-24 22:46
Putting it together:

* * * * *

In general, a "substantive" change is a change - that in the judgement of the Director - would plausibly result in reviewers changing their response during AC review.

The following, for example, are usually substantive changes to a charter:
- expansion of scope;
- addition of deliverable (which must, nonetheless, be in scope);
- extending a deliverable date to beyond the current charter period;
- changes to the decision policy of the group.

The following, for example, are usually not substantive:
- editorial changes, improving wording, correcting spelling or grammar, etc.;
- fixing broken links;
- adding clarifying text.

**Comment by cwilso** [comment] 2020-08-26 14:50
I would note that charters and WGs I've seen frequently add deliverables (in scope) and don't consider that a substantive enough change to have to recharter (as long as they're in scope).  Deliverables also frequently slip past charter periods.  :)

**Comment by dwsinger** [comment] 2020-08-26 14:52
the problem is that the Director can make non-substantive changes without announcement or review, and if it's also the Director's judgment, people might not even notice when they would have disagreed.

**Comment by frivoal** [comment] 2020-08-31 06:52
In the outcome of an AC review, the director can make editorial changes to the document under review without announcing them, and it is also the Director's judgment whether a change is editorial. Note that he can make substantive changes as well, he just has to announce and explain them.

I think this can be solved in two different ways:
1. as initially suggested here, reliably define what is or isn't substantive. For this purpose at least, since the document would be changed after having been reviewed, we probably want a fairly restrictive set of things to be changeable without saying so.
2. require that editorial changes made to a document at the ends of its AC review must also be announced.

Given that writing a precise definition of what editorial means is hard, maybe we should go with 2 instead, that seems much easier.

This would mean: the following addition in [7.1.2](https://w3c.github.io/w3process/#ACReviewAfter):
> This W3C decision is generally one of the following:
> 
> 1. The proposal is approved, possibly with editorial changes integrated. <ins>Any such change must be mentioned in the announcement.</ins>

I do realize that this is likely to be revisited once we go director-free, but the above would be a simple fix to a long standing issue. 

The second level of the problem is that even though they require documentation of the change and of its rationale, the director is allowed to make unilateral substantive changes to a document after it's been voted on. I think that too is bad, but this is definitely something that will be revisited in the director-free process, so I'm OK with not addressing it here.

As to @cwilso's point in https://github.com/w3c/w3process/issues/28#issuecomment-680928860, [5.2.3](https://w3c.github.io/w3process/#CharterReview) already lists certain *substantive* changes to a charter as being allowed without an AC Review, explicitly including the addition of in-scope deliverables. I think the way it does it is editorially a bit clumsy, and I'm thinking of proposing a clean up there as well, but I don't think there's a fundamental problem there.

**Comment by frivoal** [comment] 2021-08-11 18:34
See also #536

**Comment by frivoal** [comment] 2022-09-23 00:32
See also: this comment https://github.com/w3c/w3process/issues/532#issuecomment-842940661

**Comment by fantasai** [comment] 2022-09-24 01:18
I believe this issue is addressed by the combination of:

- https://github.com/w3c/w3process/pull/647
- https://github.com/w3c/w3process/pull/646

I believe the examples in @dwsinger’s comment https://github.com/w3c/w3process/issues/28#issuecomment-679404039 should go into /Guide.

**Closed** 2022-10-27 15:22 UTC
Labels: Closed: Accepted, P2022
