### ISSUE TITLE
Draft Registry and Candidate Registry Draft

### ISSUE THREAD

**Issue by plehegar** [w3c/w3process#516] opened 2021-04-02 19:40 UTC
[[
* The equivalent of Working Draft is called Draft Registry.

* The equivalent of Candidate Recommendation is called Candidate Registry, with Candidate Recommendation Snapshot and Candidate Recommendation Draft corresponding to Candidate Registry Snapshot and Candidate Registry Draft.
]]
https://www.w3.org/Consortium/Process/Drafts/#reg-pub

Can we call them "Registry Draft", "Candidate Registry Draft", "Candidate Registry Snapshot" ?

**Comment by dwsinger** [comment] 2021-04-02 19:55
I personally think that name differentiation is only needed and desirable for the thing that gets W3C/AC approval, the document with the registry definitions. or am I missing something mechanical? Can we avoid a profusional proliferation of names?

**Comment by fantasai** [comment] 2021-04-04 01:12
Every status has its own names, and if we're copying the REC track process (which we are), then every status in the REC track needs a corresponding name in the Registry Track. (We decided we didn't need a status corresponding to Proposed REC, so we dropped that one, but otherwise the two tracks are aligned.)

But anyway, afaict the only difference between what's in the proposal and what you're proposing is renaming "Draft Registry" to "Registry Draft"? We have "Working Draft" and "Draft Note", so I guess it's an interesting question of which to align with.

**Comment by fantasai** [comment] 2021-04-04 01:13
Fwiw, I believe you'd at one point proposed renaming "Working Draft" to "Draft Recommendation" which we all agreed would make sense if only "Working Draft" didn't have so much history. :)

**Comment by frivoal** [comment] 2021-04-15 07:08
I'm mildly against the proposed rename, but but this is fairly subjective, so I'm not going to stand in the way if the majority leans the other way. In any case, we should decide before we roll out registries, so agenda+

**Comment by fantasai** [comment] 2021-04-24 22:48
If I understand correctly, the issue is asking to rename “Draft Registry” to “Registry Draft” and no other change. That gives us the following three options:

- Working Draft / Draft Note / Draft Registry
- Working Draft / Draft Note / Registry Draft
- Working Draft / Note Draft / Registry Draft

(I also think it might be nice to make an editorial change to put the status equivalencies into a table rather than sentences.)

**Comment by dwsinger** [comment] 2021-05-10 21:57
As long as "Draft" is in the title, I have no strong opinion.

**Comment by dwsinger** [comment] 2021-05-12 14:43
closing no change

**Closed by dwsinger** 2021-05-12 14:43 UTC
Labels: Agenda+, Type: Enhancement
