### ISSUE TITLE
Increase membership of the AB, possibly TAG

### ISSUE THREAD

**Issue by cwilso** [w3c/w3process#190] opened 2018-05-14 10:00 UTC
I suggested in the AC meeting in Berlin that we should increase the number of participants in the AB if not also the TAG to account for the increased "diversity" we are garnering with STV.  There seemed to be general support, or at least some support and a lack of antipathy.

I would recommend we increase the number of AB seats by 2 (to 11 elected seats), and the TAG by 1 (to three appointed, 7 elected seats).

**Comment by nrooney** [comment] 2018-05-14 12:28
I actually support this - there's a lot of work to do and more people will help.

**Comment by dwsinger** [comment] 2018-05-14 12:32
As long as we feel we can find the candidates, I am OK with this. The downsides to larger groups is the sense that in a small group you can't be a passenger; and finding the candidates.

**Comment by bkardell** [comment] 2018-05-14 19:58
It feels like the discussion at https://lists.w3.org/Archives/Member/w3c-ac-forum/2018AprJun/0009.html is very relevant to this discussion for two reasons: 1) If any restructuring happens as in there, it seems relevant to reconsider the whole idea of appointed seats... They seem to cease to make any sense in that model.  2) If before that, even, it seems like these bodies need more seats.... well... that seems relevant to how restructuring should happen. 

I feel more the record pretty much like @dwsinger expressed: Making this group too big is going to be counter productive, but I don't know what 'right size' is either - that's a comment I've made a number of times, and a big part of that is related to being able to find good candidates. Just filling slots to fill them is no good, and neither is turning away really great options because there just aren't enough seats.

**Comment by jeffjaffe** [comment] 2018-05-16 08:30
The Advisory Board discussed this issue on 16 May 2018 and there was a consensus of support for Chris' proposal.

The AB also noted that it is important to get the TAG's input on the TAG part of the proposal.

**Comment by dwsinger** [comment] 2018-05-16 09:01
If we have continued anxiety about finding candidates, we could say that each body must have at least N and no more than M. With a larger body, we might have to consider what to do if we have too few nominations.

**Comment by frivoal** [comment] 2018-06-12 09:46
If we do an "at least N, no more than M" system, we need to be clear about what this means with STV (assuming we stick to that). If the number of candidates falls between the two numbers, is everybody elected automatically, or is there some possible result of the election that can reject candidates for not being popular enough (as long as we still have at least N)?

I have been involved in non profit board elections with an "at least N, no more than M" system using approval voting, and in that case, how it works is obvious and non controversial.

**Comment by michaelchampion** [comment] 2018-06-12 15:29
The "at least N, no more than M" system could be used to make the No Other Candidate option meaningful.  One reason that option doesn't have any actual effect is that it's not clear what would happen if No Other Candidate beat one or more actual candidates.  In the N - M system, it would simply mean the candidates that got less support than No Other Candidate wouldn't get seats so long as N seats were filled.

To be clear I MUCH prefer a simple approval ballot.  In general, we have only slightly more candidates for the AB and TAG than open seats, and it's wasteful and hurtful to spend so much energy arguing about how to choose which qualified candidates to reject. I'd suggest we set M at somewhere around 11 - 13, hold an approval ballot to ensure that the AC can non-approve any candidates that aren't qualified or don't behave appropriately, and refocus energy on solving real problems.  (If there are more than M nominees, we could select the set of M with the most approval, or those who have not already had a chance to serve, or whatever).

**Comment by dwsinger** [comment] 2018-06-12 17:36
I’ll continue to be opposed to using “and no other candidate” for reasons previously stated.

Ideally, we don’t elect un-preferred candidates because they lose to a preferred one. In most systems I know, this is caused by seeing an announcement “Mordor has joined the W3C and Sauron has been nominated to run for the AB.”, and people panic and nominate Gandalf.

We don’t announce nominations until after the close of nominations; why? Can we improve transparency and announce as they are received?

> On Jun 12, 2018, at 8:29 , Michael Champion <notifications@github.com> wrote:
> 
> The "at least N, no more than M" system could be used to make the No Other Candidate option meaningful. One reason that option doesn't have any actual effect is that it's not clear what would happen if No Other Candidate beat one or more actual candidates. In the N - M system, it would simply mean the candidates that got less support than No Other Candidate wouldn't get seats so long as N seats were filled.
> 
> To be clear I MUCH prefer a simple approval ballot. In general, we have only slightly more candidates for the AB and TAG than open seats, and it's wasteful and hurtful to spend so much energy arguing about how to choose which qualified candidates to reject. I'd suggest we set M at somewhere around 11 - 13, hold an approval ballot to ensure that the AC can non-approve any candidates that aren't qualified or don't behave appropriately, and refocus energy on solving real problems. (If there are more than M nominees, we could select the set of M with the most approval, or those who have not already had a chance to serve, or whatever).
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

David Singer
Manager, Software Standards, Apple Inc.

**Comment by bkardell** [comment] 2018-06-12 19:01
> We don’t announce nominations until after the close of nominations; why? Can we improve transparency and announce as they are received?

Yes. Yes. Please!

**Comment by cwilso** [comment] 2018-06-12 19:56
As long as the W3C continues to use STV, it is simply not as simple as "get
someone else to run".  1st choice impacts elections FAR more than
subsequent selections, so a very small set of core supporters, along with
voters who happen to list them in the "order of preference", will easily
defeat a likely-small set of people who understand how to use their vote
appropriately and want to prioritize a relatively unknown candidate.

That said, announcing nominations as they come in would be a positive IMO.
(of course, Mordor wouldn't nominate Sauron until just before nominations
close.)

**Comment by bkardell** [comment] 2018-06-13 00:52
Fully agree with what @cwilso said above. Feels like announcement is actually better as a separate topic (which I fully support) largely unrelated to increasing size or how elected, it's just a good idea.

**Comment by dwsinger** [comment] 2018-06-13 18:29
agreed, opening a separate issue on why announcements are not made immediately

**Comment by LJWatson** [comment] 2018-07-13 10:35
If the "at least N, no more than M" approach is complex with STV, perhaps we should move forward with @Cwilso's original suggestion (that the AB endorsed)? We can then at least make some progress.

**Comment by dwsinger** [comment] 2018-07-13 10:45
alas, I don't think it's complicated. If the number of people running is such that we would fall below the minimum N, that is the same as today: we can't fill the TAG/AB to its required level. If all were elected and we would end up with a TAG of M or fewer, they are elected unopposed (just like today where N=M). Otherwise, we hold an election to end up with M on the TAG/AB.

If we were to adopt "and no other candidate" we'd have to have the election when previously we would elect unopposed, and we'd have the possibility of not meeting the minimal fill level.

**Comment by michaelchampion** [comment] 2018-07-13 13:57
"At least N, no more than M" is simple with approval voting. We'd get the set of people with the most support by the AC, nothing bad happens if someone doesn't get enough approvals (there'd just be one fewer person on the TAG or AB).  There would be a problem if we get fewer then N nominees, like with any system.  If there are more than M approvals, there would be various options:
- Drop those with the fewest approvals
- Drop those who have served the longest terms before ("soft" term limits)
- Randomly select winners from those who were approved
- ...?

**Comment by frivoal** [comment] 2018-07-13 15:21
Dropping those with fewest approvals if we have too many seems the simplest and works quite well. I don't think we need to bring in any random selection into this. Soft term limits could be done that way, but I would much rather keep the whole thing very simple.

**Comment by chaals** [comment] 2018-07-14 09:33
Some pros:
* there is plenty of work to do. More people might help get more done.
* more seats allows for more diversity, and supports deeper as well as broader representation.

Some cons:
* More people might mean a further dilution of the sense of responsibility for getting stuff done.
* Scheduling meetings is difficult already. More people will complicate that further, unless we accept a higher rate of non-attendance as a reasonable trade-off.
* More seats means we need to find more nominees at each election. 

Also:
* STV with the no other candidate option, approval voting with a maximum of "N" candidates elected both fit the "between X and X+n members" proposal.
* More nominees looks likely to increase the time some people spend on the AB unless we enforce some kind of term limit.
* Randomly deciding who to kick off, without randomly deciding who is there in the first place, seems like a bad idea to me.
* Serving on the AB is an expensive undertaking. Unless we change that somehow, we may be pushing further toward giving larger members more say in what happens. Opinions differ on whether that is a good thing (legitimately, which is why this is in the "also" section)

**Comment by dwsinger** [comment] 2018-07-15 14:58
> On Jul 14, 2018, at 11:33 , chaals <notifications@github.com> wrote:
> 
> Some pros:
> 
> 	• there is plenty of work to do. More people might help get more done.
> 	• more seats allows for more diversity, and supports deeper as well as broader representation.
> Some cons:
> 
> 	• More people might mean a further dilution of the sense of responsibility for getting stuff done.
> 	• Scheduling meetings is difficult already. More people will complicate that further, unless we accept a higher rate of non-attendance as a reasonable trade-off.
> 	• More seats means we need to find more nominees at each election.
> Also:
> 
> 	• STV with the no other candidate option,

I see “no other candidate” as quite orthogonal; why are they linked? with or without NOC, we risk ending up below N (if we have too few nominated, or with NOC, approved). 

> approval voting with a maximum of "N" candidates elected both fit the "between X and X+n members" proposal.
> 	• More nominees looks likely to increase the time some people spend on the AB unless we enforce some kind of term limit.
> 	• Randomly deciding who to kick off, without randomly deciding who is there in the first place, seems like a bad idea to me.

Happily, we don’t need it for “at least N and nor more than M”.

> 	• Serving on the AB is an expensive undertaking. Unless we change that somehow, we may be pushing further toward giving larger members more say in what happens. Opinions differ on whether that is a good thing (legitimately, which is why this is in the "also" section)
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

David Singer
Manager, Software Standards, Apple Inc.

**Comment by dwsinger** [comment] 2018-08-08 19:01
after observing the work mode of the AB, which is that all of us have to say something about everything, I do not think enlarging the AB is prudent, as it will slow us down, not speed us up...

**Comment by cwilso** [comment] 2018-08-08 19:09
That seems self-fulfilling.  Increasing diversity also means you have to listen to more points of view, but that wasn't a statement against STV that I head.

**Comment by chaals** [comment] 2018-09-10 22:58
I don't support this proposal.

**Comment by dwsinger** [comment] 2018-09-10 23:04
@chaals I don't support it either (because I think a larger AB would be less effective, alas), but I am not sure I oppose it yet. At the moment, I'd like clarity on the concerns, and whether we're likely to have support, or opposition...

**Comment by LJWatson** [comment] 2018-09-11 10:54
Of the [points made by Chaals](https://github.com/w3c/w3process/issues/190#issuecomment-405011611), I think the cons can be mitigated, and the pros make it worth doing.

>Some cons:
* More people might mean a further dilution of the sense of responsibility for getting stuff done.>

It might, but then again, it might not. Increasing the number of people increases the chance of both active participants and less active ones, and whereas more of the latter will make little difference to our productivity, more of the former will.

>* Scheduling meetings is difficult already. More people will complicate that further, unless we accept a higher rate of non-attendance as a reasonable trade-off.>

We already accept a degree of non-attendance, so adjusting this accordingly wouldn't seem to make much material difference. 

We need to be better at scheduling meetings in any case, but there are ways to make this easier - such as using a relatively fixed meeting schedule. 

>* More seats means we need to find more nominees at each election.>>

It does. This is something we're aiming to do anyway, so again, it doesn't feel much like a material change, and certainly not one for the worse.

**Comment by dwsinger** [comment] 2018-09-11 16:15
We can alleviate the "we have to find more nominees" by adopting "at least N and no more than M". If there are enough nominees to fill <=M seats then they are elected unopposed. If there are >M, we have an election. (and as today, if <N, then we have an underfill problem).

**Comment by cwilso** [comment] 2018-09-11 16:16
What happens today in an underfill problem, and what could we do that would
be different?

**Comment by michaelchampion** [comment] 2018-09-11 16:40
I don't agree with the concern in 
https://github.com/w3c/w3process/issues/190#issuecomment-420089780 that a larger AB or TAG would be less effective.  There is not time and expertise available to really dig into the various issues on the agenda of either group, so the obvious answer is to add more people.

That might fall afoul of the[ Mythical Man-Month](https://en.wikipedia.org/wiki/The_Mythical_Man-Month) and make the groups even less effective because people are deluged with email and GitHub traffic on things that are not of much importance. "the increased communication overhead will consume an ever increasing quantity of the calendar time available. When n people have to communicate among themselves, as n increases, their output decreases and when it becomes negative the project is delayed further with every person added."

The main mitigation strategy for the O(N**2) communication problem is modularization/specialization: Not everyone has to be in every discussion. Also, I'm not sure it's the communication overhead that is the problem, it's a lack of consensus on key issues.  I suspect the chairs of the TAG and AB  will need to find a way other than perpetual bikeshedding to settle such issues (e.g. STV).  Binding ballots, appeal to the AC or Director, agreement to disagree, whatever.

**Comment by chaals** [comment] 2018-09-11 16:51
@michaelchampion 

> I don't understand why the Process CG id debating [this issue] ...

Because the Process CG is where a resolution to the issue gets implemented. The AC will also debate (if they choose) any issue, since they are the ones who advise the director on whether or not to accept a proposed update to the Process.

**Comment by cwilso** [comment] 2018-09-11 17:38
Not really.  The AB owns the decision-making, and the resolution they
decided on (as per Jeff's comment:
https://github.com/w3c/w3process/issues/190#issuecomment-389439047) is
implemented here in the Process CG (in
https://github.com/w3c/w3process/pull/202
<https://www.google.com/url?q=https://github.com/w3c/w3process/pull/202&sa=D&source=hangouts&ust=1536773741987000&usg=AFQjCNHs-2ygGXebFNANTbwS4_3TOkJ20g>).
The output of the Process CG is subject to the AB's approval, which then
goes for a vote in the AC.

**Comment by frivoal** [comment] 2018-09-12 03:58
Given that the folks involved in this conversation are largely the same as those who made the AB resolution, I am somewhat confused at how the AB could have consensus but we don't have consensus here.

So, did the AB have consensus back then? If yes, we're just implementing, there's nothing to be discussed, and https://github.com/w3c/w3process/commit/b2cb88629e78c74a7e45a4d5c20c4fbf303a010 is a fine implementation of that decision.

Or did we mistakenly record a consensus that wasn't actually there, and are trying to reopen the discussion?

**Comment by dwsinger** [comment] 2018-09-12 14:37
indeed, if there were a way to reject candidates, then whether or not N=M, we would need to deal with the need always to have an election, and what to do if too few candidates are elected. we don't have that situation now (nor did we in the past)

**Comment by frivoal** [comment] 2018-09-12 18:20
Closed by #202

**Closed by frivoal** 2018-09-12 18:20 UTC
